{{ config(materialized='view') }}

SELECT
    SK_ID_CURR AS APPLICANT_ID,
    SK_ID_BUREAU AS BUREAU_ID,
    CREDIT_ACTIVE AS CREDIT_STATUS,
    CREDIT_CURRENCY,
    CREDIT_TYPE,
    DAYS_CREDIT / -365.25 AS YEARS_SINCE_CREDIT_START,
    DAYS_CREDIT_ENDDATE / -365.25 AS YEARS_TO_CREDIT_END,
    COALESCE(AMT_CREDIT_SUM, 0) AS CREDIT_SUM,
    COALESCE(AMT_CREDIT_SUM_DEBT, 0) AS CREDIT_DEBT,
    COALESCE(AMT_CREDIT_SUM_OVERDUE, 0) AS CREDIT_OVERDUE,
    COALESCE(AMT_CREDIT_SUM_LIMIT, 0) AS CREDIT_LIMIT,
    CURRENT_TIMESTAMP() AS DBT_LOADED_AT
FROM {{ source('raw', 'bureau') }}
WHERE SK_ID_CURR IS NOT NULL
