{{ config(materialized='view') }}

SELECT
    SK_ID_PREV AS PREV_LOAN_ID,
    SK_ID_CURR AS APPLICANT_ID,
    MONTHS_BALANCE,
    CNT_INSTALMENT AS COUNT_INSTALMENT,
    CNT_INSTALMENT_FUTURE AS COUNT_INSTALMENT_FUTURE,
    NAME_CONTRACT_STATUS AS CONTRACT_STATUS,
    SK_DPD AS DAYS_PAST_DUE,
    SK_DPD_DEF AS DAYS_PAST_DUE_DEF,
    CURRENT_TIMESTAMP() AS DBT_LOADED_AT
FROM {{ source('raw', 'pos_cash_balance') }}
WHERE SK_ID_CURR IS NOT NULL
