{{ config(materialized='view') }}

SELECT
    SK_ID_PREV AS PREV_LOAN_ID,
    SK_ID_CURR AS APPLICANT_ID,
    MONTHS_BALANCE,
    AMT_BALANCE AS BALANCE,
    AMT_CREDIT_LIMIT_ACTUAL AS CREDIT_LIMIT_ACTUAL,
    AMT_DRAWINGS_CURRENT AS DRAWINGS_CURRENT,
    AMT_PAYMENT_CURRENT AS PAYMENT_CURRENT,
    AMT_TOTAL_RECEIVABLE AS TOTAL_RECEIVABLE,
    CNT_DRAWINGS_CURRENT AS COUNT_DRAWINGS_CURRENT,
    NAME_CONTRACT_STATUS AS CONTRACT_STATUS,
    SK_DPD AS DAYS_PAST_DUE,
    SK_DPD_DEF AS DAYS_PAST_DUE_DEF,
    CURRENT_TIMESTAMP() AS DBT_LOADED_AT
FROM {{ source('raw', 'credit_card_balance') }}
WHERE SK_ID_CURR IS NOT NULL
