{{ config(materialized='view') }}

SELECT
    SK_ID_PREV AS PREV_LOAN_ID,
    SK_ID_CURR AS APPLICANT_ID,
    NAME_CONTRACT_TYPE AS LOAN_TYPE,
    AMT_ANNUITY AS ANNUITY,
    AMT_APPLICATION AS AMOUNT_APPLIED,
    AMT_CREDIT AS AMOUNT_CREDITED,
    AMT_DOWN_PAYMENT AS DOWN_PAYMENT,
    AMT_GOODS_PRICE AS GOODS_PRICE,
    NAME_CONTRACT_STATUS AS CONTRACT_STATUS,
    NAME_PAYMENT_TYPE AS PAYMENT_TYPE,
    CODE_REJECT_REASON AS REJECT_REASON,
    NAME_CLIENT_TYPE AS CLIENT_TYPE,
    NAME_PORTFOLIO AS PORTFOLIO,
    NAME_PRODUCT_TYPE AS PRODUCT_TYPE,
    CHANNEL_TYPE,
    NAME_YIELD_GROUP AS YIELD_GROUP,
    DAYS_DECISION / -365.25 AS YEARS_SINCE_DECISION,
    CURRENT_TIMESTAMP() AS DBT_LOADED_AT
FROM {{ source('raw', 'previous_application') }}
WHERE SK_ID_CURR IS NOT NULL
