{{ config(materialized='view') }}

SELECT
    DATE::DATE AS OBS_DATE,
    OVERNIGHT_RATE::FLOAT AS OVERNIGHT_RATE,
    BOND_2YR::FLOAT AS BOND_YIELD_2YR,
    BOND_10YR::FLOAT AS BOND_YIELD_10YR,
    CADUSD::FLOAT AS FX_CAD_USD,
    CPI_TOTAL::FLOAT AS CPI_ALL,
    CURRENT_TIMESTAMP() AS DBT_LOADED_AT
FROM {{ source('raw', 'boc_macro') }}
