name: 'cancredit'
version: '1.0.0'
config-version: 2

profile: 'cancredit'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  cancredit:
    staging:
      +materialized: view
      +schema: STAGING
    intermediate:
      +materialized: table
      +schema: INTERMEDIATE
    marts:
      +materialized: table
      +schema: MARTS
      ml_features_training:
        +schema: ML_FEATURES
        +materialized: table
