-- DEPRECATED: The is_between generic test is defined in macros/test_is_between.sql
-- dbt automatically discovers generic tests from macros/ directory.
-- This file is intentionally left as a comment to prevent duplicate registration.
