-- PIVOT on EXT_SOURCE_2 deciles vs education level to show how third-party risk scores interact with demographics
-- Direct Power BI pre-computation
SELECT
    NAME_EDUCATION_TYPE,
    NTILE(5) OVER (ORDER BY EXT_SOURCE_2) AS EXT2_QUINTILE,
    COUNT(*) AS APPLICANTS,
    ROUND(AVG(TARGET) * 100, 2) AS DEFAULT_RATE_PCT,
    ROUND(AVG(EXT_SOURCE_2), 4) AS AVG_EXT_SCORE_2
FROM CANCREDIT_DB.RAW.APPLICATION_TRAIN
WHERE EXT_SOURCE_2 IS NOT NULL
GROUP BY 1, 2
ORDER BY 1, 2;
