SELECT 'APPLICATION_TRAIN'  AS tbl, COUNT(*) AS rows FROM CANCREDIT_DB.RAW.APPLICATION_TRAIN  UNION ALL
SELECT 'BUREAU',                    COUNT(*)           FROM CANCREDIT_DB.RAW.BUREAU             UNION ALL
SELECT 'BUREAU_BALANCE',            COUNT(*)           FROM CANCREDIT_DB.RAW.BUREAU_BALANCE     UNION ALL
SELECT 'PREVIOUS_APPLICATION',      COUNT(*)           FROM CANCREDIT_DB.RAW.PREVIOUS_APPLICATION UNION ALL
SELECT 'POS_CASH_BALANCE',          COUNT(*)           FROM CANCREDIT_DB.RAW.POS_CASH_BALANCE   UNION ALL
SELECT 'INSTALLMENTS_PAYMENTS',     COUNT(*)           FROM CANCREDIT_DB.RAW.INSTALLMENTS_PAYMENTS UNION ALL
SELECT 'CREDIT_CARD_BALANCE',       COUNT(*)           FROM CANCREDIT_DB.RAW.CREDIT_CARD_BALANCE UNION ALL
SELECT 'BOC_MACRO',                 COUNT(*)           FROM CANCREDIT_DB.RAW.BOC_MACRO;
